# We have created a configMap file to hold our variable values as key/value pair 
# which we need to use it in the backend application container as an environmental variable.

apiVersion: v1
kind: ConfigMap
metadata:
  name: server-side-configs
data:
  PORT: "5000"
  CLIENT: http://192.168.49.2:31909
  MONGODB_URL: mongodb://todo-mongo-service:27017/todo-k8s